version: '3'
services:

  php:
    env_file:
      - .env
    container_name: car-dealer-php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ${BACKEND_PATH}:/var/www/html/

  nginx:
    env_file:
      - .env
    container_name: car-dealer-nginx
    image: nginx:stable-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${BACKEND_PATH}:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php