version: '3'
services:

  php:
    env_file:
      - .env
    container_name: car-dealer-php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ${BACKEND_PATH}:/var/www/html/
    depends_on:
      - mysql

  nginx:
    env_file:
      - .env
    container_name: car-dealer-nginx
    image: nginx:stable-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${BACKEND_PATH}:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php

  mysql:
    env_file:
      - .env
    container_name: car-dealer-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local